// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGu-l8PousUPsDTwVC9nNrz1YHwGfftmM',
    appId: '1:220119097755:web:a86d194509c2b76cc5413e',
    messagingSenderId: '220119097755',
    projectId: 'amazify-dce64',
    authDomain: 'amazify-dce64.firebaseapp.com',
    storageBucket: 'amazify-dce64.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQsFTRTzBAutiJBSD_0P2rvmv-7Ndwj5E',
    appId: '1:220119097755:android:2a1e434e9dca744cc5413e',
    messagingSenderId: '220119097755',
    projectId: 'amazify-dce64',
    storageBucket: 'amazify-dce64.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7UecB6C2OHqrPUjSJLaex9et4tPSdA8s',
    appId: '1:220119097755:ios:2349c6f0d5dcc636c5413e',
    messagingSenderId: '220119097755',
    projectId: 'amazify-dce64',
    storageBucket: 'amazify-dce64.firebasestorage.app',
    androidClientId: '220119097755-nj30747qevicn75aj1doqmvimhldk08c.apps.googleusercontent.com',
    iosClientId: '220119097755-abql0d3m6hhkduiqp299mkucdd23o173.apps.googleusercontent.com',
    iosBundleId: 'com.example.amazify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7UecB6C2OHqrPUjSJLaex9et4tPSdA8s',
    appId: '1:220119097755:ios:2349c6f0d5dcc636c5413e',
    messagingSenderId: '220119097755',
    projectId: 'amazify-dce64',
    storageBucket: 'amazify-dce64.firebasestorage.app',
    androidClientId: '220119097755-nj30747qevicn75aj1doqmvimhldk08c.apps.googleusercontent.com',
    iosClientId: '220119097755-abql0d3m6hhkduiqp299mkucdd23o173.apps.googleusercontent.com',
    iosBundleId: 'com.example.amazify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGu-l8PousUPsDTwVC9nNrz1YHwGfftmM',
    appId: '1:220119097755:web:cc3dcf1ae1b24216c5413e',
    messagingSenderId: '220119097755',
    projectId: 'amazify-dce64',
    authDomain: 'amazify-dce64.firebaseapp.com',
    storageBucket: 'amazify-dce64.firebasestorage.app',
  );

}