import 'dart:async';
import 'package:amazify/app/presentation/widgets/bottom_nav_bar.dart';
import 'package:amazify/features/catalog/presentation/pages/home_page.dart';
import 'package:flutter/material.dart';

// THEME / APP
import 'package:amazify/features/onboarding/pages/onboarding.dart';
import 'package:amazify/app/theme/custom_theme/glass_backdrop.dart';
import 'package:amazify/app/theme/custom_theme/theme_controller.dart';
import 'package:amazify/app/theme/theme.dart';
import 'package:amazify/core/splash_screen/splash_screen.dart';

// FIREBASE
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'firebase_options.dart'; // generated by FlutterFire CLI

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Optional: crash-safe zone
  FlutterError.onError = (FlutterErrorDetails details) {
    FlutterError.dumpErrorToConsole(details);
  };

  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  runApp(const App());
}

class App extends StatefulWidget {
  const App({super.key});

  @override
  State<App> createState() => _AppState();
}

class _AppState extends State<App> {
  final ThemeController _controller = ThemeController();

  @override
  Widget build(BuildContext context) {
    return ThemeControllerScope(
      controller: _controller,
      child: AnimatedBuilder(
        animation: _controller,
        builder: (context, _) {
          // Your theme setup
          final Widget nextAfterSplash = const AuthGate();

          Widget home = const SplashPage(
            lightLogo: 'assets/icons/app_icon3.png',
            darkLogo: 'assets/icons/app_icon3_dark.png',
            audioAsset: 'audio/Netflix-Intro-Sound-Effect.mp3',
            totalMs: 5000,
            next: AuthGate(), // go to auth-aware gate after splash
          );

          if (_controller.kind == ThemeKind.glass) {
            home = GlassBackdrop(child: home);
          }

          return MaterialApp(
            title: 'E-Commerce',
            debugShowCheckedModeBanner: false,
            theme: AppTheme.light,
            darkTheme: AppTheme.dark,
            themeMode: ThemeMode.system,
            home: home,
          );
        },
      ),
    );
  }
}

/// Decides where to go based on FirebaseAuth state.
/// - If user is signed in → show your app (replace placeholder)
/// - If not signed in → Onboarding (your existing flow)
class AuthGate extends StatelessWidget {
  const AuthGate({super.key});

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<User?>(
      stream: FirebaseAuth.instance.authStateChanges(),
      builder: (context, snap) {
        // Splash/connecting state (brief)
        if (snap.connectionState == ConnectionState.waiting) {
          return const Scaffold(
            body: Center(child: CircularProgressIndicator()),
          );
        }

        // Signed in → go to your real home (replace the placeholder)
        if (snap.hasData) {
          return const RootNav();
        }

        // Signed out → your current onboarding flow
        return const OnBoardingView();
      },
    );
  }
}
